from reportlab.pdfgen import canvas

def final_decision(img_result, text_result):

    if "Abnormal" in img_result or "Severe" in text_result:
        return "🚨 HIGH RISK - Consult Doctor Immediately"

    elif "Mild" in img_result or "Moderate" in text_result:
        return "⚠ MEDIUM RISK - Further Check Recommended"

    else:
        return "✅ LOW RISK - Normal Condition"


def generate_report(patient_name, img_result, text_result, final_result):

    file = "MediVision_Report.pdf"
    c = canvas.Canvas(file)

    c.drawString(100, 780, "🏥 MediVision AI Medical Report")

    c.drawString(100, 740, f"Patient Name: {patient_name if patient_name else 'Unknown'}")

    c.drawString(100, 710, f"Image Result: {img_result}")

    c.drawString(100, 690, f"Symptom Result: {text_result}")

    c.drawString(100, 670, f"Final Result: {final_result}")

    c.drawString(100, 640, "Generated by MediVision AI System")

    c.save()

    return file